# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 20:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Link')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identifier')),
                ('internet_archive', models.URLField(blank=True, default=None, verbose_name='Archived version of page')),
                ('internet_archive_datetime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Time of archived version creation')),
                ('expiration', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Link expiration')),
                ('creation', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Date and time og link archival')),
                ('restricted', models.BooleanField(verbose_name='Access is restricted to people with a token')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, verbose_name='Access token')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='Date and time of invalidation')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiver.Link')),
            ],
        ),
    ]
